site_name: 我的博客
theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: white
      accent: blue
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.copy

nav:
  - 首页: index.md
  - 硬件开发:
      - 入门指南: 硬件开发/入门指南.md
  - AI工具使用:
      - MCP使用: AI工具使用/mcp使用.md
      - MCP客户端: AI工具使用/mcp client.md
  - 灵感记录:
      - 随笔一则: 灵感记录/随笔一则.md
      - 常州游记: 灵感记录/常州游记.md
